version: "3.2"

services:
  nginx-git:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - /etc/localtime:/etc/localtime:ro
      #- ../nginx/config:/etc/nginx/conf.d
      #- ../nginx/cert:/etc/cert
      - ../nginx/sites:/usr/share/nginx/sites
      - ../nginx/sites:/usr/share/nginx/html                       
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 1
