version: "3.2"

services:
  nginx-git:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
     # - ./nginx/config:/etc/nginx/conf.d
     # - ./nginx/cert:/etc/cert
     # - ./nginx/sites:/usr/share/nginx/sites
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 2

