version: "3.2"

services:
  nginx-git:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../nginx/sites/:/usr/share/nginx/html
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 1
