version: "3.2"

services:
  nginx-git:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 2

